baseURL = 'https://i2unix.sh/'
languageCode = 'en-us'
title = 'I2Unix-Web'

[[params.nav]]
name = "I2Unix"
url = "/"

[[params.nav]]
name = "About"
url = "/about"

[[params.nav]]
name = "Syllabus"
url = "/syllabus"

[[params.nav]]
name = "Projects"
url = "/projects"

[[params.nav]]
name = "Materials"
url = "/material"

